language: cpp

sudo: false

env:
  matrix:
    - COMPILER=g++-4.9 COVERAGE=coverage GCOV=gcov-4.9
    - COMPILER=g++-5
    - COMPILER=g++-6
    - COMPILER=g++-7

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      env: COMPILER='clang++'
    - os: osx
      osx_image: xcode7
      env: COMPILER='clang++'
    - env: COMPILER='clang++-3.9'
      addons: # because clang3.9 doesnt install together with 4-6
        apt:
          packages:
            - clang-3.9
    - env: COMPILER='clang++-4.0'
      addons:
        apt:
          packages:
            - clang-4.0
    - env: COMPILER='clang++-5.0'
      addons:
        apt:
          packages:
            - clang-5.0
    - env: COMPILER='clang++-6.0'
      addons:
        apt:
          packages:
            - clang-6.0
            
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - g++-7

before_install:
  - cmake --version
  - g++ --version
  - clang++ --version
  - if [ $TRAVIS_OS_NAME == linux ]; then
  apt-cache search "clang" | egrep "^clang-[0-9\.]+ ";
  apt-cache search "g++" | egrep "^g\+\+-[0-9\.]+ "
  fi

install:
  - if test -n "$COVERAGE"; then pip install --user cpp-coveralls; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update > /dev/null ; brew upgrade cmake; fi

before_script:
  - export CXX=$COMPILER

script:
  - mkdir cmake-build; cd cmake-build
  - cmake .. -DCMAKE_CXX_COMPILER=$CXX -DCOVERAGE=$COVERAGE
  - make VERBOSE=1 $COVERAGE
  - make all $COVERAGE
  - cd ..

after_success:
  - if test -n "$COVERAGE"; then coveralls --verbose --gcov-options '\-lp' --gcov '$GCOV' -E cmake-build/CMakefiles; fi
