version: 1.0.{build}
os:
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VisualStudioVersion: 12.0
      PlatformToolset: v120
    - VisualStudioVersion: 14.0
      PlatformToolset: v140
    - VisualStudioVersion: 15.0
      PlatformToolset: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - msbuild /p:PlatformToolset="%PlatformToolset%" "delegate.vcxproj"  /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - mkdir vcbuild
  - cd vcbuild
  - cmake .. -G "Visual Studio 12 2013"
  - msbuild /p:PlatformToolset="%PlatformToolset%" "sample.vcxproj" /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
