set(GCC_EXTRA_WARNINGS
  abi-tag
  conditionally-supported
  double-promotion
  logical-op
  noexcept
  strict-null-sentinel
  suggest-attribute=cold
  suggest-attribute=const
  suggest-attribute=format
  suggest-attribute=noreturn
  suggest-attribute=pure
  suggest-attribute=malloc
  trampolines
  unsafe-loop-optimizations
  useless-cast
  vector-operation-performance
  zero-as-null-pointer-constant
  
#experimentals as of gcc-7
  #aggregate-return # way too exciting
  duplicated-cond
  format-signedness
  invalid-pch
  missing-include-dirs
  multiple-inheritance
  null-dereference
  strict-overflow
  suggest-final-methods
  suggest-final-types
  suggest-override
  undef
  virtual-inheritance
)

set(CLANG_EXTRA_WARNINGS
  everything
  no-c++98-compat
  no-c++98-compat-pedantic
  no-unknown-pragmas
)

set(CXX_ALL_WARNINGS
  attributes
  ctor-dtor-privacy
  conversion
  cast-align
  cast-qual
  date-time
  disabled-optimization
  error
  float-conversion
  float-equal
  format-nonliteral
  format-security
  format-y2k
  inline
  missing-braces
  missing-declarations
  old-style-cast
  overloaded-virtual
  padded
  packed
  redundant-decls
  shadow
  sign-conversion
  sign-promo
  stack-protector
  switch-default
  switch-enum
  synth
  unused-macros
)
